#!/usr/bin/env python3
"""genstruct.py - the C mirror of ccon-handler.e's OBJECT console.

E lays an OBJECT out in declaration order: an untyped field or a PTR is
a LONG (4 bytes), NAME[n]:ARRAY OF X is n elements inline, and fields are
word-aligned. Writes engine/con.h; the handler checks a few offsets at
run time (fcheck) and keeps the C engine off if any disagree."""
import re, sys
src = open(sys.argv[1], encoding='latin1').read()
body = re.search(r'^OBJECT console\n(.*?)^ENDOBJECT', src, re.S | re.M).group(1)
sizes = {'LONG': 4, 'INT': 2, 'CHAR': 1}
ctype = {'LONG': 'LONG', 'INT': 'WORD', 'CHAR': 'UBYTE'}
off = 0
out = ['/* generated by genstruct.py from OBJECT console - do not edit */',
       '#ifndef EXEC_TYPES_H', 'typedef long LONG; typedef short WORD; typedef unsigned char UBYTE;', '#endif',
       'struct con {']
offs = {}
for line in body.split('\n'):
    line = line.split('->')[0].strip()
    if not line:
        continue
    for f in [x.strip() for x in line.split(',')]:
        if not f:
            continue
        m = re.match(r'(\w+)\[(\d+)\]:ARRAY OF (\w+)$', f)
        if m:
            name, n, t = m.group(1), int(m.group(2)), m.group(3)
            if off & 1: off += 1
            offs[name] = off
            out.append('  %s %s[%d]; /* %d */' % (ctype[t], name, n, off))
            off += n * sizes[t]
            continue
        m = re.match(r'(\w+)(?::(.*))?$', f)
        assert m, f
        name, t = m.group(1), (m.group(2) or 'LONG').strip()
        if off & 1: off += 1
        offs[name] = off
        if t == 'CHAR':
            out.append('  UBYTE %s; /* %d */' % (name, off)); off += 1
        elif t == 'INT':
            out.append('  WORD %s; /* %d */' % (name, off)); off += 2
        else:
            out.append('  LONG %s; /* %d */' % (name, off)); off += 4
out.append('}; /* size %d */' % off)
open(sys.argv[2], 'w').write('\n'.join(out) + '\n')
print('size', off, 'cx', offs['cx'], 'sb', offs['sb'], 'mmask', offs['mmask'], 'vblank', offs['vblank'])
